/** @typedef {{id:string, before:string, mid:string, after?:string, zh:string}} Example */

/** Perfekt 例句：完整句 = before + aux + mid + participle + after */
window.EXAMPLES = {
  abfahren: { before: "Gestern", mid: "der Zug um acht Uhr", after: ".", zh: "昨天火車八點出發了。" },
  anfangen: { before: "Er", mid: "gestern mit der Arbeit", after: ".", zh: "他昨天開始工作了。" },
  ankommen: { before: "Wir", mid: "spät am Bahnhof", after: ".", zh: "我們很晚才到火車站。" },
  annehmen: { before: "Sie", mid: "das Angebot", after: ".", zh: "她接受了這個提議。" },
  ansehen: { before: "Er", mid: "sich den Film genau", after: ".", zh: "他仔細看了這部電影。" },
  anziehen: { before: "Das Kind", mid: "schnell die Jacke", after: ".", zh: "孩子很快穿上了外套。" },
  aufschreiben: { before: "Ich", mid: "die Adresse", after: ".", zh: "我把地址寫下來了。" },
  aufstehen: { before: "Sie", mid: "heute früh", after: ".", zh: "她今天很早起床了。" },
  ausgehen: { before: "Wir", mid: "am Samstagabend", after: ".", zh: "我們週六晚出去了。" },
  aussehen: { before: "Das Essen", mid: "sehr gut", after: ".", zh: "這食物看起來很好。" },
  aussteigen: { before: "Er", mid: "an der nächsten Station", after: ".", zh: "他在下一站下車了。" },
  ausziehen: { before: "Sie", mid: "die nassen Schuhe", after: ".", zh: "她脫下了濕鞋子。" },
  bekommen: { before: "Ich", mid: "gestern einen Brief", after: ".", zh: "我昨天收到一封信。" },
  beschreiben: { before: "Er", mid: "das Problem klar", after: ".", zh: "他清楚地描述了這個問題。" },
  bleiben: { before: "Wir", mid: "zu Hause", after: ".", zh: "我們留在家裡了。" },
  bringen: { before: "Sie", mid: "mir einen Kaffee", after: ".", zh: "她給我帶來一杯咖啡。" },
  denken: { before: "Ich", mid: "lange darüber", after: ".", zh: "我想了很久這件事。" },
  drankommen: { before: "Endlich", mid: "er an der Kasse", after: ".", zh: "終於輪到他結帳了。" },
  einfallen: { before: "Plötzlich", mid: "mir sein Name", after: ".", zh: "我突然想起他的名字。" },
  eingeben: { before: "Sie", mid: "das Passwort", after: ".", zh: "她輸入了密碼。" },
  einladen: { before: "Er", mid: "uns zum Essen", after: ".", zh: "他邀請我們吃飯了。" },
  einschlafen: { before: "Das Baby", mid: "schnell", after: ".", zh: "寶寶很快就入睡了。" },
  einsteigen: { before: "Wir", mid: "in den Bus", after: ".", zh: "我們上了公車。" },
  empfehlen: { before: "Der Arzt", mid: "mir Sport", after: ".", zh: "醫生向我推薦運動。" },
  erschliessen: { before: "Man", mid: "die Bedeutung aus dem Text", after: ".", zh: "人們從語境推斷出意思。" },
  essen: { before: "Wir", mid: "in einem Restaurant", after: ".", zh: "我們在餐廳吃了飯。" },
  fahren: { before: "Sie", mid: "nach Berlin", after: ".", zh: "她去了柏林。" },
  fernsehen: { before: "Er", mid: "den ganzen Abend", after: ".", zh: "他看了一整晚電視。" },
  finden: { before: "Ich", mid: "meinen Schlüssel", after: ".", zh: "我找到了我的鑰匙。" },
  fliegen: { before: "Wir", mid: "nach Spanien", after: ".", zh: "我們飛去西班牙了。" },
  freihaben: { before: "Sie", mid: "gestern", after: ".", zh: "她昨天放假了。" },
  geben: { before: "Er", mid: "mir das Buch", after: ".", zh: "他給了我這本書。" },
  gefallen: { before: "Der Film", mid: "mir sehr", after: ".", zh: "這部電影我很喜歡。" },
  gehen: { before: "Wir", mid: "ins Kino", after: ".", zh: "我們去電影院了。" },
  geniessen: { before: "Sie", mid: "den Urlaub", after: ".", zh: "她享受了假期。" },
  heissen: { before: "Früher", mid: "die Straße anders", after: ".", zh: "這條街以前叫別的名字。" },
  helfen: { before: "Er", mid: "seiner Mutter", after: ".", zh: "他幫助了他的媽媽。" },
  hochfahren: { before: "Ich", mid: "den Computer", after: ".", zh: "我啟動了電腦。" },
  kennen: { before: "Wir", mid: "uns seit der Schule", after: ".", zh: "我們從學校起就認識。" },
  klingen: { before: "Das Lied", mid: "sehr schön", after: ".", zh: "這首歌聽起來很美。" },
  kommen: { before: "Sie", mid: "zu spät", after: ".", zh: "她來得太晚了。" },
  laufen: { before: "Er", mid: "im Park", after: ".", zh: "他在公園跑了。" },
  leidtun: { before: "Es", mid: "mir wirklich", after: ".", zh: "我真的很抱歉。" },
  lesen: { before: "Ich", mid: "das Buch zu Ende", after: ".", zh: "我把這本書讀完了。" },
  liegen: { before: "Das Buch", mid: "auf dem Tisch", after: ".", zh: "書在桌子上。" },
  lossein: { before: "Was", mid: "gestern", after: "?", zh: "昨天出什麼事了？" },
  losfahren: { before: "Wir", mid: "früh am Morgen", after: ".", zh: "我們一大早就出發了。" },
  losgehen: { before: "Der Kurs", mid: "um neun", after: ".", zh: "課程九點開始了。" },
  mitbringen: { before: "Sie", mid: "Kuchen zur Party", after: ".", zh: "她帶蛋糕來派對了。" },
  mitkommen: { before: "Er", mid: "mit uns ins Kino", after: ".", zh: "他跟我們一起去電影院了。" },
  mitlesen: { before: "Die Klasse", mid: "den Text laut", after: ".", zh: "全班一起朗讀了課文。" },
  mitnehmen: { before: "Ich", mid: "den Schirm", after: ".", zh: "我帶上了雨傘。" },
  mitsprechen: { before: "Die Kinder", mid: "das Gedicht", after: ".", zh: "孩子們跟著說了這首詩。" },
  nachsprechen: { before: "Wir", mid: "die neuen Wörter", after: ".", zh: "我們跟著重複了生詞。" },
  nehmen: { before: "Er", mid: "einen Apfel", after: ".", zh: "他拿了一個蘋果。" },
  nennen: { before: "Sie", mid: "ihren Namen", after: ".", zh: "她說出了自己的名字。" },
  raten: { before: "Ich", mid: "die richtige Antwort", after: ".", zh: "我猜對了答案。" },
  rausgehen: { before: "Er", mid: "kurz in den Garten", after: ".", zh: "他短暫出去到花園了。" },
  riechen: { before: "Sie", mid: "die Blumen", after: ".", zh: "她聞了這些花。" },
  scheinen: { before: "Die Sonne", mid: "den ganzen Tag", after: ".", zh: "太陽照了一整天。" },
  schlafen: { before: "Das Kind", mid: "gut", after: ".", zh: "孩子睡得很好。" },
  schliessen: { before: "Er", mid: "die Tür", after: ".", zh: "他關了門。" },
  schneiden: { before: "Sie", mid: "das Brot", after: ".", zh: "她切了麵包。" },
  schreiben: { before: "Ich", mid: "eine E-Mail", after: ".", zh: "我寫了一封電子郵件。" },
  schwimmen: { before: "Wir", mid: "im See", after: ".", zh: "我們在湖裡游泳了。" },
  sehen: { before: "Er", mid: "einen Vogel", after: ".", zh: "他看見一隻鳥。" },
  singen: { before: "Sie", mid: "ein Lied", after: ".", zh: "她唱了一首歌。" },
  sitzen: { before: "Wir", mid: "lange im Café", after: ".", zh: "我們在咖啡館坐了很久。" },
  sprechen: { before: "Er", mid: "mit dem Lehrer", after: ".", zh: "他和老師談過了。" },
  stattfinden: { before: "Das Konzert", mid: "gestern Abend", after: ".", zh: "音樂會昨晚舉行了。" },
  stehen: { before: "Das Auto", mid: "vor dem Haus", after: ".", zh: "車停在房子前面。" },
  tragen: { before: "Sie", mid: "eine rote Tasche", after: ".", zh: "她帶著一個紅色包包。" },
  treffen: { before: "Ich", mid: "einen alten Freund", after: ".", zh: "我遇見一位老朋友。" },
  trinken: { before: "Er", mid: "einen Tee", after: ".", zh: "他喝了一杯茶。" },
  tun: { before: "Was", mid: "du gestern", after: "?", zh: "你昨天做了什麼？" },
  ueberweisen: { before: "Ich", mid: "das Geld", after: ".", zh: "我把錢轉帳了。" },
  umsteigen: { before: "Wir", mid: "in München", after: ".", zh: "我們在慕尼黑換乘了。" },
  umziehen: { before: "Sie", mid: "in eine neue Wohnung", after: ".", zh: "她搬進了新公寓。" },
  unterschreiben: { before: "Er", mid: "den Vertrag", after: ".", zh: "他簽了合約。" },
  unterstreichen: { before: "Die Lehrerin", mid: "wichtige Wörter", after: ".", zh: "老師在重要單詞下畫了線。" },
  verbinden: { before: "Der Arzt", mid: "die Wunde", after: ".", zh: "醫生包紮了傷口。" },
  vergessen: { before: "Ich", mid: "meine Hausaufgaben", after: ".", zh: "我忘了作業。" },
  vergleichen: { before: "Wir", mid: "die Preise", after: ".", zh: "我們比較了價格。" },
  verstehen: { before: "Sie", mid: "die Frage", after: ".", zh: "她聽懂了這個問題。" },
  vorlesen: { before: "Die Mutter", mid: "eine Geschichte", after: ".", zh: "媽媽朗讀了一個故事。" },
  waschen: { before: "Er", mid: "das Auto", after: ".", zh: "他洗了車。" },
  wehtun: { before: "Der Zahn", mid: "den ganzen Tag", after: ".", zh: "牙齒疼了一整天。" },
  wiedergeben: { before: "Er", mid: "den Text mit eigenen Worten", after: ".", zh: "他用自己的話複述了課文。" },
  wiegen: { before: "Das Paket", mid: "zwei Kilo", after: ".", zh: "這個包裹重兩公斤。" },
  wissen: { before: "Ich", mid: "die Antwort", after: ".", zh: "我知道答案。" },
  ziehen: { before: "Er", mid: "den Wagen", after: ".", zh: "他拉了那輛車。" },
  zuhaben: { before: "Das Geschäft", mid: "schon", after: ".", zh: "商店已經關門了。" },
  zurueckfahren: { before: "Wir", mid: "am Sonntag", after: ".", zh: "我們星期天開回去了。" },
  zurueckfinden: { before: "Er", mid: "den Weg zum Hotel", after: ".", zh: "他找到了回飯店的路。" },
  haben: { before: "Sie", mid: "viel Glück", after: ".", zh: "她很幸運。" },
  sein: { before: "Er", mid: "gestern krank", after: ".", zh: "他昨天生病了。" },
  werden: { before: "Es", mid: "kalt", after: ".", zh: "天氣變冷了。" },
  duerfen: { before: "Er", mid: "das nicht", after: ".", zh: "他那時不可以那樣做。" },
  koennen: { before: "Sie", mid: "das schon immer", after: ".", zh: "她一直都會這個。" },
  muessen: { before: "Wir", mid: "gestern viel", after: ".", zh: "我們昨天必須做很多事。" },
  sollen: { before: "Du", mid: "das früher", after: ".", zh: "你本來應該早點那樣做。" },
  wollen: { before: "Er", mid: "nur helfen", after: ".", zh: "他只是想幫忙。" },
  moechten: { before: "Sie", mid: "ein Eis", after: ".", zh: "她想要一支冰淇淋。" },
  moegen: { before: "Ich", mid: "den Kuchen sehr", after: ".", zh: "我很喜歡這個蛋糕。" },
};
