/** @typedef {{id:string,infinitive:string,present:string,aux:'hat'|'ist',participle:string,zh:string,separable?:boolean,group?:string}} Verb */

/** @type {Verb[]} */
window.VERBS = [
  { id: "abfahren", infinitive: "abfahren", present: "er fährt ab", aux: "ist", participle: "abgefahren", zh: "出發；開走", separable: true },
  { id: "anfangen", infinitive: "anfangen", present: "er fängt an", aux: "hat", participle: "angefangen", zh: "開始", separable: true },
  { id: "ankommen", infinitive: "ankommen", present: "er kommt an", aux: "ist", participle: "angekommen", zh: "到達", separable: true },
  { id: "annehmen", infinitive: "annehmen", present: "er nimmt an", aux: "hat", participle: "angenommen", zh: "接受；假定", separable: true },
  { id: "ansehen", infinitive: "ansehen", present: "er sieht an", aux: "hat", participle: "angesehen", zh: "看；察看", separable: true },
  { id: "anziehen", infinitive: "anziehen", present: "er zieht an", aux: "hat", participle: "angezogen", zh: "穿上（衣服）", separable: true },
  { id: "aufschreiben", infinitive: "aufschreiben", present: "er schreibt auf", aux: "hat", participle: "aufgeschrieben", zh: "寫下來", separable: true },
  { id: "aufstehen", infinitive: "aufstehen", present: "er steht auf", aux: "ist", participle: "aufgestanden", zh: "起床；站起來", separable: true },
  { id: "ausgehen", infinitive: "ausgehen", present: "er geht aus", aux: "ist", participle: "ausgegangen", zh: "出門；外出", separable: true },
  { id: "aussehen", infinitive: "aussehen", present: "er sieht aus", aux: "hat", participle: "ausgesehen", zh: "看起來；顯得", separable: true },
  { id: "aussteigen", infinitive: "aussteigen", present: "er steigt aus", aux: "ist", participle: "ausgestiegen", zh: "下車；下車廂", separable: true },
  { id: "ausziehen", infinitive: "ausziehen", present: "er zieht aus", aux: "hat", participle: "ausgezogen", zh: "脫下（衣服）", separable: true },
  { id: "bekommen", infinitive: "bekommen", present: "er bekommt", aux: "hat", participle: "bekommen", zh: "得到；收到" },
  { id: "beschreiben", infinitive: "beschreiben", present: "er beschreibt", aux: "hat", participle: "beschrieben", zh: "描述；描寫" },
  { id: "bleiben", infinitive: "bleiben", present: "er bleibt", aux: "ist", participle: "geblieben", zh: "停留；保持" },
  { id: "bringen", infinitive: "bringen", present: "er bringt", aux: "hat", participle: "gebracht", zh: "帶來；拿來" },
  { id: "denken", infinitive: "denken", present: "er denkt", aux: "hat", participle: "gedacht", zh: "想；思考" },
  { id: "drankommen", infinitive: "drankommen", present: "er kommt dran", aux: "ist", participle: "drangekommen", zh: "輪到；輪到某人", separable: true },
  { id: "einfallen", infinitive: "einfallen", present: "er fällt ein", aux: "ist", participle: "eingefallen", zh: "想起；突然想到", separable: true },
  { id: "eingeben", infinitive: "eingeben", present: "er gibt ein", aux: "hat", participle: "eingegeben", zh: "輸入（資料）", separable: true },
  { id: "einladen", infinitive: "einladen", present: "er lädt ein", aux: "hat", participle: "eingeladen", zh: "邀請", separable: true },
  { id: "einschlafen", infinitive: "einschlafen", present: "er schläft ein", aux: "ist", participle: "eingeschlafen", zh: "入睡", separable: true },
  { id: "einsteigen", infinitive: "einsteigen", present: "er steigt ein", aux: "ist", participle: "eingestiegen", zh: "上車；上車廂", separable: true },
  { id: "empfehlen", infinitive: "empfehlen", present: "er empfiehlt", aux: "hat", participle: "empfohlen", zh: "推薦" },
  { id: "erschliessen", infinitive: "erschließen", present: "er erschließt", aux: "hat", participle: "erschlossen", zh: "開發；推斷出" },
  { id: "essen", infinitive: "essen", present: "er isst", aux: "hat", participle: "gegessen", zh: "吃" },
  { id: "fahren", infinitive: "fahren", present: "er fährt", aux: "ist", participle: "gefahren", zh: "開車；乘坐" },
  { id: "fernsehen", infinitive: "fernsehen", present: "er sieht fern", aux: "hat", participle: "ferngesehen", zh: "看電視", separable: true },
  { id: "finden", infinitive: "finden", present: "er findet", aux: "hat", participle: "gefunden", zh: "找到；覺得" },
  { id: "fliegen", infinitive: "fliegen", present: "er fliegt", aux: "ist", participle: "geflogen", zh: "飛；乘飛機" },
  { id: "freihaben", infinitive: "freihaben", present: "er hat frei", aux: "hat", participle: "freigehabt", zh: "放假；有空", separable: true },
  { id: "geben", infinitive: "geben", present: "er gibt", aux: "hat", participle: "gegeben", zh: "給" },
  { id: "gefallen", infinitive: "gefallen", present: "er gefällt", aux: "hat", participle: "gefallen", zh: "喜歡；令…喜歡" },
  { id: "gehen", infinitive: "gehen", present: "er geht", aux: "ist", participle: "gegangen", zh: "走；去" },
  { id: "geniessen", infinitive: "genießen", present: "er genießt", aux: "hat", participle: "genossen", zh: "享受" },
  { id: "heissen", infinitive: "heißen", present: "er heißt", aux: "hat", participle: "geheißen", zh: "名叫；叫做" },
  { id: "helfen", infinitive: "helfen", present: "er hilft", aux: "hat", participle: "geholfen", zh: "幫助" },
  { id: "hochfahren", infinitive: "hochfahren", present: "er fährt hoch", aux: "hat", participle: "hochgefahren", zh: "啟動（電腦等）", separable: true },
  { id: "kennen", infinitive: "kennen", present: "er kennt", aux: "hat", participle: "gekannt", zh: "認識；熟悉" },
  { id: "klingen", infinitive: "klingen", present: "er klingt", aux: "hat", participle: "geklungen", zh: "聽起來；作響" },
  { id: "kommen", infinitive: "kommen", present: "er kommt", aux: "ist", participle: "gekommen", zh: "來" },
  { id: "laufen", infinitive: "laufen", present: "er läuft", aux: "ist", participle: "gelaufen", zh: "跑；走" },
  { id: "leidtun", infinitive: "leidtun", present: "er tut leid", aux: "hat", participle: "leidgetan", zh: "抱歉；難過（es tut mir leid）", separable: true },
  { id: "lesen", infinitive: "lesen", present: "er liest", aux: "hat", participle: "gelesen", zh: "讀；閱讀" },
  { id: "liegen", infinitive: "liegen", present: "er liegt", aux: "hat", participle: "gelegen", zh: "躺；位於" },
  { id: "lossein", infinitive: "los sein", present: "er ist los", aux: "ist", participle: "los gewesen", zh: "怎麼回事；出什麼事" },
  { id: "losfahren", infinitive: "losfahren", present: "er fährt los", aux: "ist", participle: "losgefahren", zh: "動身開車；啟程", separable: true },
  { id: "losgehen", infinitive: "losgehen", present: "er geht los", aux: "ist", participle: "losgegangen", zh: "出發；開始走", separable: true },
  { id: "mitbringen", infinitive: "mitbringen", present: "er bringt mit", aux: "hat", participle: "mitgebracht", zh: "帶來；隨身帶", separable: true },
  { id: "mitkommen", infinitive: "mitkommen", present: "er kommt mit", aux: "ist", participle: "mitgekommen", zh: "一起來；跟著來", separable: true },
  { id: "mitlesen", infinitive: "mitlesen", present: "er liest mit", aux: "hat", participle: "mitgelesen", zh: "一起讀；跟著看", separable: true },
  { id: "mitnehmen", infinitive: "mitnehmen", present: "er nimmt mit", aux: "hat", participle: "mitgenommen", zh: "帶走；帶上", separable: true },
  { id: "mitsprechen", infinitive: "mitsprechen", present: "er spricht mit", aux: "hat", participle: "mitgesprochen", zh: "一起說；跟著說", separable: true },
  { id: "nachsprechen", infinitive: "nachsprechen", present: "er spricht nach", aux: "hat", participle: "nachgesprochen", zh: "跟著重複說", separable: true },
  { id: "nehmen", infinitive: "nehmen", present: "er nimmt", aux: "hat", participle: "genommen", zh: "拿；取" },
  { id: "nennen", infinitive: "nennen", present: "er nennt", aux: "hat", participle: "genannt", zh: "稱呼；說出名字" },
  { id: "raten", infinitive: "raten", present: "er rät", aux: "hat", participle: "geraten", zh: "猜測；建議" },
  { id: "rausgehen", infinitive: "rausgehen", present: "er geht raus", aux: "ist", participle: "rausgegangen", zh: "出去（口語）", separable: true },
  { id: "riechen", infinitive: "riechen", present: "er riecht", aux: "hat", participle: "gerochen", zh: "聞；有…氣味" },
  { id: "scheinen", infinitive: "scheinen", present: "er scheint", aux: "hat", participle: "geschienen", zh: "照耀；似乎" },
  { id: "schlafen", infinitive: "schlafen", present: "er schläft", aux: "hat", participle: "geschlafen", zh: "睡覺" },
  { id: "schliessen", infinitive: "schließen", present: "er schließt", aux: "hat", participle: "geschlossen", zh: "關閉；結束" },
  { id: "schneiden", infinitive: "schneiden", present: "er schneidet", aux: "hat", participle: "geschnitten", zh: "切；剪" },
  { id: "schreiben", infinitive: "schreiben", present: "er schreibt", aux: "hat", participle: "geschrieben", zh: "寫" },
  { id: "schwimmen", infinitive: "schwimmen", present: "er schwimmt", aux: "ist", participle: "geschwommen", zh: "游泳" },
  { id: "sehen", infinitive: "sehen", present: "er sieht", aux: "hat", participle: "gesehen", zh: "看見" },
  { id: "singen", infinitive: "singen", present: "er singt", aux: "hat", participle: "gesungen", zh: "唱歌" },
  { id: "sitzen", infinitive: "sitzen", present: "er sitzt", aux: "hat", participle: "gesessen", zh: "坐" },
  { id: "sprechen", infinitive: "sprechen", present: "er spricht", aux: "hat", participle: "gesprochen", zh: "說；說話" },
  { id: "stattfinden", infinitive: "stattfinden", present: "er findet statt", aux: "hat", participle: "stattgefunden", zh: "舉行；發生", separable: true },
  { id: "stehen", infinitive: "stehen", present: "er steht", aux: "hat", participle: "gestanden", zh: "站；立" },
  { id: "tragen", infinitive: "tragen", present: "er trägt", aux: "hat", participle: "getragen", zh: "帶；穿；抬" },
  { id: "treffen", infinitive: "treffen", present: "er trifft", aux: "hat", participle: "getroffen", zh: "遇見；約會" },
  { id: "trinken", infinitive: "trinken", present: "er trinkt", aux: "hat", participle: "getrunken", zh: "喝" },
  { id: "tun", infinitive: "tun", present: "er tut", aux: "hat", participle: "getan", zh: "做" },
  { id: "ueberweisen", infinitive: "überweisen", present: "er überweist", aux: "hat", participle: "überwiesen", zh: "轉帳；轉診" },
  { id: "umsteigen", infinitive: "umsteigen", present: "er steigt um", aux: "ist", participle: "umgestiegen", zh: "換乘", separable: true },
  { id: "umziehen", infinitive: "umziehen", present: "er zieht um", aux: "ist", participle: "umgezogen", zh: "搬家", separable: true },
  { id: "unterschreiben", infinitive: "unterschreiben", present: "er unterschreibt", aux: "hat", participle: "unterschrieben", zh: "簽名" },
  { id: "unterstreichen", infinitive: "unterstreichen", present: "er unterstreicht", aux: "hat", participle: "unterstrichen", zh: "畫底線；強調" },
  { id: "verbinden", infinitive: "verbinden", present: "er verbindet", aux: "hat", participle: "verbunden", zh: "連接；包紮" },
  { id: "vergessen", infinitive: "vergessen", present: "er vergisst", aux: "hat", participle: "vergessen", zh: "忘記" },
  { id: "vergleichen", infinitive: "vergleichen", present: "er vergleicht", aux: "hat", participle: "verglichen", zh: "比較" },
  { id: "verstehen", infinitive: "verstehen", present: "er versteht", aux: "hat", participle: "verstanden", zh: "理解；聽懂" },
  { id: "vorlesen", infinitive: "vorlesen", present: "er liest vor", aux: "hat", participle: "vorgelesen", zh: "朗讀；讀給別人聽", separable: true },
  { id: "waschen", infinitive: "waschen", present: "er wäscht", aux: "hat", participle: "gewaschen", zh: "洗" },
  { id: "wehtun", infinitive: "wehtun", present: "er tut weh", aux: "hat", participle: "wehgetan", zh: "疼；痛", separable: true },
  { id: "wiedergeben", infinitive: "wiedergeben", present: "er gibt wieder", aux: "hat", participle: "wiedergegeben", zh: "複述；再現", separable: true },
  { id: "wiegen", infinitive: "wiegen", present: "er wiegt", aux: "hat", participle: "gewogen", zh: "稱重；重量為" },
  { id: "wissen", infinitive: "wissen", present: "er weiß", aux: "hat", participle: "gewusst", zh: "知道" },
  { id: "ziehen", infinitive: "ziehen", present: "er zieht", aux: "hat", participle: "gezogen", zh: "拉；拖" },
  { id: "zuhaben", infinitive: "zuhaben", present: "er hat zu", aux: "hat", participle: "zugehabt", zh: "關著（門等）", separable: true },
  { id: "zurueckfahren", infinitive: "zurückfahren", present: "er fährt zurück", aux: "ist", participle: "zurückgefahren", zh: "開回去；返回", separable: true },
  { id: "zurueckfinden", infinitive: "zurückfinden", present: "er findet zurück", aux: "hat", participle: "zurückgefunden", zh: "找回路；找回", separable: true },
  { id: "haben", infinitive: "haben", present: "er hat", aux: "hat", participle: "gehabt", zh: "有", group: "special" },
  { id: "sein", infinitive: "sein", present: "er ist", aux: "ist", participle: "gewesen", zh: "是；在", group: "special" },
  { id: "werden", infinitive: "werden", present: "er wird", aux: "ist", participle: "geworden", zh: "變成；將要", group: "special" },
  { id: "duerfen", infinitive: "dürfen", present: "er darf", aux: "hat", participle: "gedurft", zh: "可以；被允許", group: "modal" },
  { id: "koennen", infinitive: "können", present: "er kann", aux: "hat", participle: "gekonnt", zh: "能夠；會", group: "modal" },
  { id: "muessen", infinitive: "müssen", present: "er muss", aux: "hat", participle: "gemusst", zh: "必須", group: "modal" },
  { id: "sollen", infinitive: "sollen", present: "er soll", aux: "hat", participle: "gesollt", zh: "應該", group: "modal" },
  { id: "wollen", infinitive: "wollen", present: "er will", aux: "hat", participle: "gewollt", zh: "想要", group: "modal" },
  { id: "moechten", infinitive: "möchten", present: "er möchte", aux: "hat", participle: "gemocht", zh: "想要（禮貌）", group: "modal" },
  { id: "moegen", infinitive: "mögen", present: "er mag", aux: "hat", participle: "gemocht", zh: "喜歡", group: "modal" },
];
